// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNTfoiva8D4ZjrbjRDieTPFnfjxTv89k',
    appId: '1:888831126131:web:5c5e6cc9b3a1b47fac5806',
    messagingSenderId: '888831126131',
    projectId: 'newsnexus-bee6c',
    authDomain: 'newsnexus-bee6c.firebaseapp.com',
    storageBucket: 'newsnexus-bee6c.firebasestorage.app',
    measurementId: 'G-9QE8NVKFGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4nNxBIBQqdl9yNge1aGSghtJTwuqXJuY',
    appId: '1:888831126131:android:71eda139b9f217b5ac5806',
    messagingSenderId: '888831126131',
    projectId: 'newsnexus-bee6c',
    storageBucket: 'newsnexus-bee6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJ1DTPVEY6cFnoI8wMUOsOs21SA-M7cM',
    appId: '1:888831126131:ios:ece5c37a5c55ef50ac5806',
    messagingSenderId: '888831126131',
    projectId: 'newsnexus-bee6c',
    storageBucket: 'newsnexus-bee6c.firebasestorage.app',
    iosClientId: '888831126131-62dgqno80mu9n61h37g1i0qnu0sp8j93.apps.googleusercontent.com',
    iosBundleId: 'com.example.newNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJ1DTPVEY6cFnoI8wMUOsOs21SA-M7cM',
    appId: '1:888831126131:ios:ece5c37a5c55ef50ac5806',
    messagingSenderId: '888831126131',
    projectId: 'newsnexus-bee6c',
    storageBucket: 'newsnexus-bee6c.firebasestorage.app',
    iosClientId: '888831126131-62dgqno80mu9n61h37g1i0qnu0sp8j93.apps.googleusercontent.com',
    iosBundleId: 'com.example.newNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNTfoiva8D4ZjrbjRDieTPFnfjxTv89k',
    appId: '1:888831126131:web:b6598723dfd7ed85ac5806',
    messagingSenderId: '888831126131',
    projectId: 'newsnexus-bee6c',
    authDomain: 'newsnexus-bee6c.firebaseapp.com',
    storageBucket: 'newsnexus-bee6c.firebasestorage.app',
    measurementId: 'G-LH2V79R387',
  );
}
